language: node_js
#  latest stable Node.js release
node_js: lts/*
addons:
  chrome: stable # make Chrome available
# Cache node packages between jobs
cache: npm

script:
  - npm run lint
  # - npm run test
  - travis_wait npm run generate
  - npm run bundlewatch
  - npm run lhci:autorun
  - npx semantic-release

deploy:
  - provider: surge
    project: ./dist
    edge: true # opt in to dpl v2
    skip_cleanup: true
    cleanup: false
    on:
      all_branches: true

after_deploy:
  - npm run test:e2e
